# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  - name: Education
    url: '#education'
    weight: 2
  - name: Experience
    url: '#experience'
    weight: 3
  - name: Publications
    url: '#publications'
    weight: 4
  - name: Contact
    url: '#contact'
    weight: 100
  - name: CV
    url: 'uploads/CV.pdf'
    weight: 101
    
